type GoalJourneyProps = {
  title: string;
  currentStep: number;
  steps: string[];
};

export default function GoalJourney({
  title,
  currentStep,
  steps,
}: GoalJourneyProps) {
  const currentXP = (currentStep + 1) * 150;
  const nextLevelXP = (currentStep + 2) * 150;

  return (
    <div className="rounded-[32px] border border-violet-100 bg-white/90 backdrop-blur-xl p-8 shadow-xl shadow-violet-100/60 transition-all duration-300 hover:-translate-y-1 hover:shadow-2xl hover:shadow-violet-200/60">

      {/* Header */}

      <div className="flex items-start justify-between">

        <div>

          <h2 className="text-3xl font-bold text-slate-900">
            {title}
          </h2>

          <p className="mt-2 text-slate-500">
            Level {currentStep + 1} / {steps.length}
          </p>

          <div className="mt-3 inline-flex rounded-full bg-violet-100 px-3 py-1 text-xs font-semibold text-violet-700">
            ✨ Generated by Yumee
          </div>

        </div>

        <div className="text-right">

          <p className="text-sm font-semibold uppercase tracking-wider text-violet-500">
            Current Quest
          </p>

          <p className="mt-2 text-lg font-bold text-slate-900">
            {steps[currentStep]}
          </p>

        </div>

      </div>

      {/* XP */}

      <div className="mt-8 flex justify-between text-sm">

        <span className="font-medium text-slate-500">
          XP Progress
        </span>

        <span className="font-semibold text-violet-600">
          {currentXP} / {nextLevelXP} XP
        </span>

      </div>

      <div className="mt-3 h-3 overflow-hidden rounded-full bg-violet-100">

        <div
          className="h-full rounded-full bg-gradient-to-r from-violet-500 via-fuchsia-500 to-purple-500 transition-all duration-700"
          style={{
            width: `${((currentStep + 1) / steps.length) * 100}%`,
          }}
        />

      </div>

      {/* Journey */}

      <div className="mt-10 flex items-center justify-between overflow-x-auto pb-4">

        {steps.map((step, index) => {

          const completed = index < currentStep;
          const active = index === currentStep;

          return (

            <div
              key={index}
              className="flex items-center"
            >

              <div className="flex min-w-[115px] flex-col items-center">

                <div
                  className={`
                    flex h-16 w-16 items-center justify-center rounded-full text-xl font-bold transition-all duration-300
                    ${
                      completed
                        ? "bg-emerald-100 text-emerald-600 border border-emerald-200"
                        : active
                        ? "bg-gradient-to-br from-violet-500 to-fuchsia-500 text-white shadow-xl shadow-violet-300 ring-4 ring-violet-100"
                        : "bg-slate-100 text-slate-400 border border-slate-200"
                    }
                  `}
                >
                  {completed ? "✓" : active ? "⭐" : index + 1}
                </div>

                <p
                  className={`
                    mt-4 text-center text-sm font-medium leading-5
                    ${
                      completed
                        ? "text-emerald-600"
                        : active
                        ? "text-violet-600"
                        : "text-slate-500"
                    }
                  `}
                >
                  {step}
                </p>

              </div>

              {index !== steps.length - 1 && (

                <div
                  className={`
                    mx-3 h-1 w-16 rounded-full
                    ${
                      completed
                        ? "bg-violet-400"
                        : "bg-violet-100"
                    }
                  `}
                />

              )}

            </div>

          );

        })}

      </div>

      {/* Bottom Cards */}

      <div className="mt-8 grid gap-5 md:grid-cols-2">

        <div className="rounded-2xl border border-violet-100 bg-violet-50 p-5">

          <p className="text-sm font-medium text-slate-500">
            Next Unlock
          </p>

          <h3 className="mt-2 text-lg font-bold text-slate-900">
            {steps[currentStep + 1] || "🏆 Goal Completed"}
          </h3>

        </div>

        <div className="rounded-2xl border border-amber-100 bg-amber-50 p-5">

          <p className="text-sm font-medium text-slate-500">
            Completion Reward
          </p>

          <h3 className="mt-2 text-lg font-bold text-amber-600">
            +150 XP & Achievement Badge 🏅
          </h3>

        </div>

      </div>

    </div>
  );
}