type GoalJourneyProps = {
  title: string;
  currentStep: number;
  steps: string[];
};

export default function GoalJourney({
  title,
  currentStep,
  steps,
}: GoalJourneyProps) {

  const currentXP = (currentStep + 1) * 150;
  const nextLevelXP = (currentStep + 2) * 150;

  return (
    <div className="bg-[#1E293B] rounded-3xl p-6">

      <div className="flex justify-between items-start mb-6">

        <div>
          <h2 className="text-2xl font-bold">
            {title}
          </h2>

          <p className="text-slate-400 mt-1">
            Level {currentStep + 1} / {steps.length}
          </p>

          <p className="text-xs text-violet-400 mt-2">
            Generated by Yumee ✨
          </p>
        </div>

        <div className="text-right">
          <p className="text-blue-400 font-semibold">
            Current Quest
          </p>

          <p className="text-white font-medium">
            {steps[currentStep]}
          </p>
        </div>

      </div>

      <div className="mb-2 flex justify-between text-sm">
        <span className="text-slate-400">
          XP Progress
        </span>

        <span className="text-violet-400">
          {currentXP} / {nextLevelXP} XP
        </span>
      </div>

      <div className="mb-8">
        <div className="w-full h-3 bg-slate-700 rounded-full overflow-hidden">
          <div
            className="h-full bg-gradient-to-r from-blue-500 to-violet-500"
            style={{
              width: `${((currentStep + 1) / steps.length) * 100}%`,
            }}
          />
        </div>
      </div>

      <div className="flex items-center justify-between overflow-x-auto pb-6">

        {steps.map((step, index) => {

          const completed = index < currentStep;
          const active = index === currentStep;

          return (
            <div
              key={index}
              className="flex items-center"
            >
              <div className="flex flex-col items-center min-w-[100px]">

                <div
                  className={`
                    w-14 h-14 rounded-full flex items-center justify-center text-lg font-bold transition-all
                    ${
                      completed
                        ? "bg-green-500"
                        : active
                        ? "bg-blue-500 ring-4 ring-blue-500/30"
                        : "bg-slate-700"
                    }
                  `}
                >
                  {completed ? "✓" : active ? "⭐" : index + 1}
                </div>

                <p
                  className={`
                    mt-3 text-center text-sm
                    ${
                      completed
                        ? "text-green-400"
                        : active
                        ? "text-blue-400"
                        : "text-slate-400"
                    }
                  `}
                >
                  {step}
                </p>

              </div>

              {index !== steps.length - 1 && (
                <div className="w-16 h-1 bg-slate-700 mx-2" />
              )}
            </div>
          );
        })}

      </div>

      <div className="grid md:grid-cols-2 gap-4">

        <div className="bg-[#0F172A] rounded-2xl p-4">
          <p className="text-slate-400 text-sm">
            Next Unlock
          </p>

          <p className="text-white mt-1 font-semibold">
            {steps[currentStep + 1] || "Goal Completed 🏆"}
          </p>
        </div>

        <div className="bg-[#0F172A] rounded-2xl p-4">
          <p className="text-slate-400 text-sm">
            Completion Reward
          </p>

          <p className="text-yellow-400 mt-1 font-semibold">
            +150 XP & Achievement Badge 🏅
          </p>
        </div>

      </div>

    </div>
  );
}